name: expense_manager
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.5+1
  collection: ^1.19.1
  localstorage: ^6.0.0
  equatable: ^2.0.7
  get_it: ^8.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  build_runner: ^2.4.15
  mockito: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#7c3397"
  image: "assets/images/expense_manager_splash.png"

  android_12:
    color: "#7c3397"
    image: "assets/images/expense_manager_splash.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/expense_manager_logo.png"
  adaptive_icon_background: "#7c3397"
  adaptive_icon_foreground: "assets/images/expense_manager_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
