// Mocks generated by Mockito 5.4.6 from annotations
// in expense_manager/test/features/expense_manager/presentation/providers/tag_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:expense_manager/features/expense_manager/domain/entites/tag.dart'
    as _i5;
import 'package:expense_manager/features/expense_manager/domain/repositories/expense_repository.dart'
    as _i2;
import 'package:expense_manager/features/expense_manager/domain/usecases/add_tag.dart'
    as _i6;
import 'package:expense_manager/features/expense_manager/domain/usecases/delete_tag.dart'
    as _i7;
import 'package:expense_manager/features/expense_manager/domain/usecases/get_tags.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExpenseRepository_0 extends _i1.SmartFake
    implements _i2.ExpenseRepository {
  _FakeExpenseRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetTags].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTags extends _i1.Mock implements _i3.GetTags {
  MockGetTags() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExpenseRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeExpenseRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ExpenseRepository);

  @override
  _i4.Future<List<_i5.Tag>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i5.Tag>>.value(<_i5.Tag>[]),
          )
          as _i4.Future<List<_i5.Tag>>);
}

/// A class which mocks [AddTag].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTag extends _i1.Mock implements _i6.AddTag {
  MockAddTag() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExpenseRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeExpenseRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ExpenseRepository);

  @override
  _i4.Future<void> call(_i5.Tag? tag) =>
      (super.noSuchMethod(
            Invocation.method(#call, [tag]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [DeleteTag].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTag extends _i1.Mock implements _i7.DeleteTag {
  MockDeleteTag() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExpenseRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeExpenseRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ExpenseRepository);

  @override
  _i4.Future<void> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
